applications/home/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from applications.home import views


urlpatterns = [

    url(r'^contact/$', (views.ContactView.as_view()), name='contact'),
    url(r'^hot-tours/$', (views.HotTripView.as_view()), name='hot-tours'),
    url(r'^special/$', (views.SpecialOffersView.as_view()), name='special'),
    url(r'^$', (views.HomeView.as_view()), name='home'),
]

mayakshethra2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url('grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'^', include('applications.home.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/models.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField
from solo.models import SingletonModel


class About(SingletonModel):
    title = models.CharField(max_length=255)
    description = RichTextUploadingField()
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return 'About'

    class Meta:
        verbose_name = "About"


class Package(models.Model):
    title = models.CharField(max_length=255)
    description = RichTextUploadingField()
    image = models.ImageField()
    video = models.URLField(null=True, blank=True)
    price = models.IntegerField()
    is_special = models.BooleanField(default=False)
    place = models.CharField(max_length=255)

    def __str__(self):
        return 'Package'

    class Meta:
        verbose_name = "Package"
        verbose_name_plural = "Packages"


class BannerImages(models.Model):
    image = models.ImageField()
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return 'Banner Images'

    class Meta:
        verbose_name = "Banner Images"


class ContactDetails(SingletonModel):
    phone = models.CharField(max_length=255)
    email = models.EmailField()
    address = RichTextUploadingField()

    def __str__(self):
        return 'Contact Details'

    class Meta:
        verbose_name = "Contact Details"


class Testimonial(models.Model):
    author = models.CharField(max_length=255)
    testimonial = models.TextField()
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = "Testimonial"
        verbose_name_plural = "Testimonials"


class Gallery(models.Model):
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = "Gallery"
        verbose_name_plural = "Gallery"


class Enquiry(models.Model):
    name = models.CharField(max_length=235)
    subject = models.CharField(max_length=235)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Enquiry'
        verbose_name_plural = 'Enquiries'


class Booking(models.Model):
    CHOICES = (
        ('cheap', 'Cheap'),
        ('standard', 'Standard'),
        ('lux', 'Lux'),
    )

    name = models.CharField(max_length=235)
    email = models.EmailField()
    check_in = models.DateField()
    check_out = models.DateField()
    comfort_type = models.CharField(max_length=20, choices=CHOICES, null=True, blank=True)
    no_of_adults = models.IntegerField(default=0)
    no_of_children = models.IntegerField(default=0)
    no_of_rooms = models.IntegerField(default=0)
    message = models.TextField()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'booking'
        verbose_name_plural = 'Bookings'

applications/home/forms.py
from django import forms

from .models import Enquiry


class ContactForm(forms.ModelForm):

    class Meta:
        model = Enquiry
        fields = ('name', 'subject', 'email', 'message')

applications/home/views.py
import json

from django.views import generic
from django.http import HttpResponse
from django.http import JsonResponse
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from .forms import ContactForm
from .models import About, Package, Testimonial, Gallery, \
    ContactDetails, BannerImages, Booking


class HomeView(generic.TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['about'] = About.get_solo()
        context['contact'] = ContactDetails.get_solo()
        context['bg_images'] = BannerImages.objects.all()
        context['packages'] = Package.objects.all()[:3]
        context['testimonials'] = Testimonial.objects.all()
        context['galleries'] = Gallery.objects.all()
        return context


class HotTripView(generic.ListView):
    template_name = 'hot_tours.html'
    model = Package
    context_object_name = 'packages'


class SpecialOffersView(generic.ListView):
    template_name = 'special.html'
    model = Package
    queryset = Package.objects.filter(is_special=True)
    context_object_name = 'specials'

    def get_context_data(self, **kwargs):
        context = super(SpecialOffersView, self).get_context_data(**kwargs)
        place = self.request.GET.get('place')
        if place:
            specials = Package.objects.filter(is_special=True, place=place)
            context['specials'] = specials
        context['places'] = set(Package.objects.all().values_list('place', flat=True))

        return context

class ContactView(generic.FormView):

    form_class = ContactForm
    template_name = "contact.html"

    def form_valid(self, form):
        print('dddddddddddddddddddddddddddddddddddddddddddd')
        text_template = get_template('email_templates/contact_message.html')
        user_name = form.cleaned_data['name']
        subject = 'Contact request from {}'.format(user_name)
        context = {'formentry': self.request.POST}
        text_content = text_template.render(context)
        from_email = settings.EMAIL_HOST_USER
        email = ContactDetails.get_solo().email
        to = [email]
        msg = EmailMultiAlternatives(subject, text_content, from_email, to)
        msg.attach_alternative(text_content, "text/html")
        msg.send()
        form.save()
        return JsonResponse({'status':'success'})

    def form_invalid(self, form):
        print(form.errors)
        return HttpResponse(json.dumps({'result': {'status': 'form_error', 'errors': form.errors}}),
                            content_type='application/json')

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>About</title>
		<meta charset="utf-8">
		<meta name="format-detection" content="telephone=no" />
		<link rel="icon" href="images/favicon.ico">
		<link rel="shortcut icon" href="images/favicon.ico" />
		<link rel="stylesheet" href="{% static 'booking/css/booking.css' %}">
		<link rel="stylesheet" href="{% static 'css/camera.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<script src="{% static 'js/jquery.js' %}"></script>
		<script src="{% static 'js/jquery-migrate-1.2.1.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<script src="{% static 'js/superfish.js' %}"></script>
		<script src="{% static 'js/jquery.ui.totop.js' %}"></script>
		<script src="{% static 'js/jquery.equalheights.js' %}"></script>
		<script src="{% static 'js/jquery.mobilemenu.js' %}"></script>
		<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'js/owl.carousel.js' %}"></script>
		<script src="{% static 'js/camera.js' %}"></script>
		<!--[if (gt IE 9)|!(IE)]><!-->
		<script src="{% static 'js/jquery.mobile.customized.min.js' %}"></script>
		<!--<![endif]-->
		<!--<script src="{% static 'booking/js/jquery-ui-1.10.3.custom.min.js' %}"></script>-->
		<!--<script src="{% static 'booking/js/jquery.fancyform.js' %}"></script>-->
		<!--<script src="{% static 'booking/js/jquery.placeholder.js' %}"></script>-->
		<!--<script src="{% static 'booking/js/regula.js' %}"></script>-->
		{% if  request.path != '/contact/' %}
		<script src="{% static 'booking/js/booking.js' %}"></script>
		{% endif %}
		{% block extra_js %}{% endblock %}
		<script>
			$(document).ready(function(){
			jQuery('#camera_wrap').camera({
				loader: false,
				pagination: false ,
				minHeight: '444',
				thumbnails: false,
				height: '48.375%',
				caption: true,
				navigation: true,
				fx: 'mosaic'
			});
			<!--jQuery('#tesimonial_wrap').camera({-->
				<!--loader: true,-->
				<!--pagination: false ,-->
				<!--minHeight: '100',-->
				<!--thumbnails: true,-->
				<!--height: '48.375%',-->
				<!--caption: true,-->
				<!--navigation: false,-->
				<!--fx: 'mosaic'-->
			<!--});-->
			/*carousel*/
			var owl=$("#owl");
				owl.owlCarousel({
				items : 2, //10 items above 1000px browser width
				itemsDesktop : [995,2], //5 items between 1000px and 901px
				itemsDesktopSmall : [767, 2], // betweem 900px and 601px
				itemsTablet: [700, 2], //2 items between 600 and 0
				itemsMobile : [479, 1], // itemsMobile disabled - inherit from itemsTablet option
				navigation : true,
				pagination : false
				});
			$().UItoTop({ easingType: 'easeOutQuart' });
			});
		</script>
		<!--[if lt IE 8]>
		<div style=' clear: both; text-align:center; position: relative;'>
			<a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
				<img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
			</a>
		</div>
		<![endif]-->
		<!--[if lt IE 9]>
		<script src="{% static 'js/html5shiv.js' %}"></script>
		<link rel="stylesheet" media="screen" href="{% static 'css/ie.css' %}">
		<![endif]-->
	</head>
	<body class="page1" id="top">
<!--==============================header=================================-->
		<header>
			<div class="container_12">
				<div class="grid_12">
					<div class="menu_block">
						<nav class="horizontal-nav full-width horizontalNav-notprocessed">
							<ul class="sf-menu">
								<li class="current"><a href="/">HOME</a></li>
								<li><a href="{% url 'hot-tours' %}">HOT TOURS</a></li>
								<li><a href="{% url 'special' %}">SPECIAL OFFERS</a></li>
								<li><a href="index-3.html">BLOG</a></li>
								<li><a href="{% url 'contact' %}">CONTACTS</a></li>
							</ul>
						</nav>
						<div class="clear"></div>
					</div>
				</div>
				<!--<div class="grid_12">-->
					<!--<h1>-->
						<!--<a href="/">-->
							<!--<img src="{% static 'images/logo.png' %}" alt="Your Happy Family">-->
						<!--</a>-->
					<!--</h1>-->
				<!--</div>-->
			</div>
		</header>
    {% block content %} {% endblock %}
    	<footer>
			<div class="container_12">
				<div class="grid_12">
					<div class="socials">
						<a href="#" class="fa fa-facebook"></a>
						<a href="#" class="fa fa-twitter"></a>
						<a href="#" class="fa fa-google-plus"></a>
					</div>
					<div class="copy">
						Your Trip (c) 2014 | <a href="#">Privacy Policy</a> | Website Template Designed by TemplateMonster.com
					</div>
				</div>
			</div>
		</footer>
		<script>
			$(function (){
				$('#bookingForm').bookingForm({
					ownerEmail: '#'
				});
			})
			$(function() {
				$('#bookingForm input, #bookingForm textarea').placeholder();
			});
		</script>
	{% block extrajs %}

	{% endblock %}
	</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block extra_js %}
<script src="{% static 'booking/js/cb.js' %}"></script>
{% endblock %}
{% block content %}
<!--==============================Content=================================-->
		<div class="content">
			<div class="container_12">
				<div class="grid_5">
					<h3>CONTACT INFO</h3>
					<div class="map">
						<p><span class="blog">Maecenas vehicula egestas venenatis. Duis massa elit, auctor non pellentesque vel aliquet sit amet erat. Nullam eget dignissim nisi, aliquam feugiat nibh. </span></p>
						<div class="clear"></div>
						<figure class="">
							<iframe src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Brooklyn,+New+York,+NY,+United+States&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=61.282355,146.513672&amp;ie=UTF8&amp;hq=&amp;hnear=Brooklyn,+Kings,+New+York&amp;ll=40.649974,-73.950005&amp;spn=0.01628,0.025663&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
						</figure>
						<address>
							<dl>
								<dt>The Company Name Inc. <br>
									8901 Marmora Road,<br>
									Glasgow, D04 89GR.
								</dt>
								<dd><span>Freephone:</span>+1 800 559 6580</dd>
								<dd><span>Telephone:</span>+1 800 603 6035</dd>
								<dd><span>FAX:</span>+1 800 889 9898</dd>
								<dd>E-mail: <a href="#" class="col1">mail@demolink.org</a></dd>
							</dl>
						</address>
					</div>
				</div>
				<div class="grid_6 prefix_1">
					<h3>GET IN TOUCH</h3>
					<form id="contactform" action="" method="post">
								{% csrf_token %}
							<div class="row form-group">
								<div class="col-md-6">
									<input type="text" id="id_name" onkeyup="removeError('name')"
										   name="name" class="form-control" placeholder="Your name">
									<span id="name" class="error"></span>
								</div>
							</div>

							<div class="row form-group">
								<div class="col-md-12">
									<input type="text" id="id_email" name="email" onkeyup="removeError('email')" class="form-control" placeholder="Your email address">
									<span id="email" class="error"></span>
								</div>
							</div>

							<div class="row form-group">
								<div class="col-md-12">
									<input type="text" id="id_subject" name="subject" onkeyup="removeError('subject')" class="form-control" placeholder="Your subject of this message">
									<span id="subject" class="error"></span>
								</div>
							</div>

							<div class="row form-group">
								<div class="col-md-12">
									<textarea name="message" id="id_message" cols="30" onkeyup="removeError('message')" rows="10" class="form-control" placeholder="Say something about us"></textarea>
									<span id="message" class="error"></span>
								</div>
							</div>
							<div class="form-group">
								<button id="btn-submit" class="btn btn-primary"> Send Message </button>
							</div>
						</form>
				</div>
			</div>
		</div>
{% endblock %}
{% block extrajs %}

<script>

function removeError(id){
	document.getElementById(id).innerHTML = "";
}

var count = 0;
$('#btn-submit').click(function() {
	<!--document.getElementById("success-message").innerHTML = "";-->
	var data = $('#contactform').serialize();
	var url = "{% url 'contact' %}"
	$('.error').html("");
    $('#successful').html("");
    document.getElementById("btn-submit").innerHTML = "SENDING...";
	$.ajax({
		type: 'POST',
		url: url,
		data: data,
		cache : false,
		processData: false,

		success: function (response) {
			if (response.status == 'success') {
				$('.error').remove();
				document.getElementById("btn-submit").innerHTML = "Send Message";
				<!--document.getElementById("success-message").innerHTML = "Message Sent Successfully";-->
				$('#contactform')[0].reset();
			}
			else if (response.result.status == 'form_error') {
				document.getElementById("btn-submit").innerHTML = "Send Message";

				$("#contactform :input:not(input[type='hidden'],input[type='submit'])").each(function () {
					var current = $(this).parent();
					var current_name = $(this).attr('name');
					$.each(response.result.errors, function (index, value) {
						if (current_name == index) {
							$('#'+current_name).html(value);
						}
					});
				});
			}
		},
		error: function(error){}
	});
	return false;
});
</script>
{% endblock %}

templates/email_templates/contact_message.html
<!doctype html>


<html>
<head>
    <meta charset="utf-8">
    <title>Title</title>
</head>

<body>
<table  border="0" width="500px" align="center" style=" table-layout:fixed;font-family:Arial, sans-serif; text-align:center;">
    <tr>
        <td>
            <!--<img  src="http://206.189.129.28/static/image/catalog/logo.jpg" width="80%" height="70" alt="Logo"/>-->
        </td>
    </tr>
    <tr>
        <td>
            <hr style="border-top: 1px solid #f1f1f1; background: transparent;"/>
        </td>
    </tr>
    <tr>
        <td><h1 style="color:#666;  font-size:30px;">You have a new contact message from <br>{{ formentry.name }}</h1></td>
    </tr>
    <tr>
        <td style="color:#999;font-size:20px; ">Subject : {{ formentry.subject }}</td>
    </tr>
    <tr>
    <tr>
        <td style="color:#999;font-size:20px; "> email : {{ formentry.email }}</td>
    </tr>
    <tr>
        <td style="color:#999;font-size:20px; ">Message</td></tr>
    <tr>
       <td width="50%" style="color:#999;font-size:20px;word-wrap:break-word;white-space:pre-wrap;word-break:break-all;"> {{ formentry.message }}</td>
    </tr>

    <tr>
        <td><a target="_blank" href="mailto:{{ formentry.email }}" style="border-radius:5px; background:#0F99D3; text-decoration:none;  color:white; padding:8px 18px; margin:10px auto 20px auto; display:block; width:200px;">Click Here</a></td>
    </tr>
    <tr>
        <td>
            <hr style="border-top: 1px solid #f1f1f1; background: transparent;"/>
        </td>
    </tr>
</table>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
		<div class="slider_wrapper">
			<div id="camera_wrap" class="">
				{% for i in bg_images %}
				<div data-src="{{i.image.url}}">
					<div class="caption fadeIn">
						<h2>{{i.title}}</h2>
						<div class="price">
							<span>{{i.sub_title}}</span>
						</div>
						<!--<a href="#">LEARN MORE</a>-->
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
<!--==============================Content=================================-->
		<div class="content"><div class="ic">More Website Templates @ TemplateMonster.com - February 10, 2014!</div>
			<div class="container_12">
				{% for p in packages %}
				<div class="grid_4">
					<div class="banner">
						<img src="{{ p.image.url }}" alt="">
						<div class="label">
							<div class="title">{{p.title}}</div>
							<div class="price">FROM<span>$ {{p.price}}</span></div>
							<a href="#">LEARN MORE</a>
						</div>
					</div>
				</div>
				{% endfor %}
				<div class="clear"></div>
				<div class="grid_6">
					<h3>Booking Form</h3>
					<form id="bookingForm">
						<div class="fl1">
							<div class="tmInput">
								<input name="Name" placeHolder="Name:" type="text" data-constraints='@NotEmpty @Required @AlphaSpecial'>
							</div>
							<div class="tmInput">
								<input name="Country" placeHolder="Country:" type="text" data-constraints="@NotEmpty @Required">
							</div>
						</div>
						<div class="fl1">
							<div class="tmInput">
								<input name="Email" placeHolder="Email:" type="text" data-constraints="@NotEmpty @Required @Email">
							</div>
							<div class="tmInput mr0">
								<input name="Hotel" placeHolder="Hotel:" type="text" data-constraints="@NotEmpty @Required">
							</div>
						</div>
						<div class="clear"></div>
						<strong>Check-in</strong>
						<label class="tmDatepicker">
							<input type="text" name="Check-in" placeHolder='10/05/2014' data-constraints="@NotEmpty @Required @Date">
						</label>
						<div class="clear"></div>
						<strong>Check-out</strong>
						<label class="tmDatepicker">
							<input type="text" name="Check-out" placeHolder='20/05/2014' data-constraints="@NotEmpty @Required @Date">
						</label>
						<div class="clear"></div>
						<div class="tmRadio">
							<p>Comfort</p>
							<input name="Comfort" type="radio" id="tmRadio0" data-constraints='@RadioGroupChecked(name="Comfort", groups=[RadioGroup])' checked/>
							<span>Cheap</span>
							<input name="Comfort" type="radio" id="tmRadio1" data-constraints='@RadioGroupChecked(name="Comfort", groups=[RadioGroup])' />
							<span>Standart</span>
							<input name="Comfort" type="radio" id="tmRadio2" data-constraints='@RadioGroupChecked(name="Comfort", groups=[RadioGroup])' />
							<span>Lux</span>
						</div>
						<div class="clear"></div>
						<div class="fl1 fl2">
							<em>Adults</em>
							<select name="Adults" class="tmSelect auto" data-class="tmSelect tmSelect2" data-constraints="">
								<option>1</option>
								<option>1</option>
								<option>2</option>
								<option>3</option>
							</select>
							<div class="clear"></div>
							<em>Rooms</em>
							<select name="Rooms" class="tmSelect auto" data-class="tmSelect tmSelect2" data-constraints="">
								<option>1</option>
								<option>1</option>
								<option>2</option>
								<option>3</option>
							</select>
						</div>
						<div class="fl1 fl2">
							<em>Children</em>
							<select name="Children" class="tmSelect auto" data-class="tmSelect tmSelect2" data-constraints="">
								<option>0</option>
								<option>0</option>
								<option>1</option>
								<option>2</option>
							</select>
						</div>
						<div class="clear"></div>
						<div class="tmTextarea">
							<textarea name="Message" placeHolder="Message" data-constraints='@NotEmpty @Required @Length(min=20,max=999999)'></textarea>
						</div>
						<a href="#" class="btn" data-type="submit">Submit</a>
					</form>
				</div>
				<div class="grid_5 prefix_1">
					<h3>{{about.title}}</h3>
					{% if about.image %}
					<img src="{{about.image.url}}" alt="" class="img_inner fleft">
					{% endif %}
					<div class="clear cl1"></div>
					<p>{{about.description|safe}}</p>
				  <!--<h4>Clients’ Quotes</h4>-->
					<!--<div class="slider_wrapper">-->
						<!--<div id="tesimonial_wrap" class="">-->
					<!--{% for t in testimonials %}-->

					<!--<blockquote class="bq1">-->
						<!--<img src="{{t.image}}" alt="" class="img_inner author-image noresize fleft">-->
						<!--<div class="extra_wrapper">-->
							<!--<p>{{t.testimonial}}</p>-->
							<!--<div class="alright">-->
								<!--<div class="col1">{{t.author}}</div>-->
								<!--<a href="#" class="btn">More</a>-->
							<!--</div>-->
						<!--</div>-->
					<!--</blockquote>-->
					<!--{% endfor %}-->
					<!--</div>-->
						<!--</div>-->
				</div>
				<div class="grid_12">
					<h3 class="head1">Latest News</h3>
				</div>
				<div class="grid_4">
					<div class="block1">
						<time datetime="2014-01-01">10<span>Jan</span></time>
						<div class="extra_wrapper">
							<div class="text1 col1"><a href="#">Aliquam nibh</a></div>
							Proin pharetra luctus diam, any scelerisque eros convallisumsan. Maecenas vehicula egestas
						</div>
					</div>
				</div>
				<div class="grid_4">
					<div class="block1">
						<time datetime="2014-01-01">21<span>Jan</span></time>
						<div class="extra_wrapper">
							<div class="text1 col1"><a href="#">Etiam dui eros</a></div>
							Any scelerisque eros vallisumsan. Maecenas vehicula egestas natis. Duis massa elit, auctor non
						</div>
					</div>
				</div>
				<div class="grid_4">
					<div class="block1">
						<time datetime="2014-01-01">15<span>Feb</span></time>
						<div class="extra_wrapper">
							<div class="text1 col1"><a href="#">uamnibh Edeto</a></div>
							Ros convallisumsan. Maecenas vehicula egestas venenatis. Duis massa elit, auctor non
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}
<!--==============================footer=================================-->

templates/hot_tours.html
{% extends 'base.html' %}
{% block content %}
<!--==============================Content=================================-->
		<div class="content">
			<div class="container_12">
				<div class="banners">
					{% for p in packages %}
					<div class="grid_4">
						<div class="banner">
							<img src="{{p.image.url}}" alt="">
							<div class="label">
								<div class="title">{{p.title}}</div>
								<div class="price">from<span>$ {{p.price}}</span></div>
								<a href="#">LEARN MORE</a>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>
<!--==============================footer=================================-->
{% endblock %}

templates/special.html
{% extends 'base.html' %}
{% block content %}

<!--==============================Content=================================-->
		<div class="content">
			<div class="container_12">
				<div class="grid_8">
					<h3>Special offers</h3>
					{% for s in specials %}
					<div class="block2">
						<img src="{{s.image.url}}" alt="" class="img_inner fleft special-image">
						<div class="extra_wrapper">
							<div class="text1 col1"><a href="{% url 'special' %}?place={{s.place}}">
								{{s.place}}</a></div>
							<p>{{s.description|safe}}
							<br>
							<a href="#" class="link1">LEARN MORE</a>
						</div>
					</div>
					{% endfor %}
				</div>
				<div class="grid_3 prefix_1">
					<h5>CHOOse the country</h5>
					<ul class="list">
						{% for p in places %}
						<li><a href="{% url 'special' %}?place={{p}}">{{p}}</a></li>
						{% endfor %}
					</ul>
					<a href="{% url 'special' %}" class="link1">VIEW A<span class="low">ll</span></a>
				</div>
			</div>
		</div>
{% endblock %}